<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class FixFakeUserPasswords extends Command
{
    protected $signature = 'users:fix-passwords';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Fixes the hashed passwords generated by the Python script to use Laravel bcrypt';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info('Starting password hash update...');
        $hash = \Illuminate\Support\Facades\Hash::make('password');
        
        $updated = \Illuminate\Support\Facades\DB::table('users')->update([
            'password_hash' => $hash,
        ]);
        
        $this->info("Successfully updated {$updated} users with the correct 'password' hash.");
    }
}
