<?php

namespace Database\Seeders;

use App\Models\AuditLog;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Loads the ~500k-row fake dataset generated by fake-data/generate_fake_data.py
 * (JSON fixtures in database/seeders/fake_data/) into Postgres for
 * load-testing search/pagination/UI performance, and emits a matching
 * MongoDB audit_log entry for every row in a table AuditObserver watches -
 * the same shape it would have written had these rows been created through
 * the app itself.
 *
 * Run with: php artisan db:seed --class=FakeDataSeeder
 * Not part of the default DatabaseSeeder - this is a large, optional,
 * load-testing dataset, not demo/bootstrap data.
 */
class FakeDataSeeder extends Seeder
{
    private const FIXTURE_DIR = __DIR__.'/fake_data';

    private const CHUNK_SIZE = 1000;

    /**
     * Set to true to skip MongoDB audit_log writes entirely.
     * Use this when seeding large datasets (500K+ rows) to avoid
     * overwhelming MongoDB with bulk audit documents.
     */
    private const SKIP_AUDIT_LOG = true;

    /**
     * table => column holding the moment the row was "created", used as the
     * audit_log created_at. Null means the table has no such column
     * (AuditObserver would have used now() at creation time in the app).
     */
    private const AUDIT_TABLES = [
        'journals' => 'created_at',
        'user_roles' => null,
        'manuscripts' => 'created_at',
        'manuscript_versions' => 'uploaded_at',
        'manuscript_files' => null,
        'authors' => null,
        'co_author_invitations' => 'invited_at',
        'editor_assignments' => 'assigned_at',
        'review_invitations' => 'invited_at',
        'reviews' => 'submitted_at',
        'editorial_decisions' => 'decided_at',
        'articles' => 'published_at',
        'issues' => 'publication_date',
    ];

    /** table => entity_type string AuditObserver derives via Str::snake(class_basename($model)). */
    private const ENTITY_TYPES = [
        'journals' => 'journal',
        'user_roles' => 'user_role',
        'manuscripts' => 'manuscript',
        'manuscript_versions' => 'manuscript_version',
        'manuscript_files' => 'manuscript_file',
        'authors' => 'author',
        'co_author_invitations' => 'co_author_invitation',
        'editor_assignments' => 'editor_assignment',
        'review_invitations' => 'review_invitation',
        'reviews' => 'review',
        'editorial_decisions' => 'editorial_decision',
        'articles' => 'article',
        'issues' => 'issue',
    ];

    /** FK-safe load order; matches generate_fake_data.py's write order. */
    private const TABLE_ORDER = [
        'users', 'journals', 'user_roles', 'keywords', 'issues', 'manuscripts', 'manuscript_versions',
        'manuscript_files', 'authors', 'manuscript_keywords', 'co_author_invitations',
        'editor_assignments', 'review_invitations', 'reviews', 'review_scores', 'review_files',
        'editorial_decisions', 'messages', 'articles', 'citations', 'article_metrics',
    ];

    /** Tables with an explicit id column whose sequence must be bumped past our fixed IDs. */
    private const SEQUENCE_TABLES = [
        'users', 'journals', 'user_roles', 'issues', 'keywords', 'manuscripts', 'manuscript_versions',
        'manuscript_files', 'authors', 'co_author_invitations', 'editor_assignments',
        'review_invitations', 'reviews', 'review_scores', 'review_files',
        'editorial_decisions', 'messages', 'articles', 'citations', 'article_metrics',
    ];

    public function run(): void
    {
        if (! is_dir(self::FIXTURE_DIR)) {
            $this->command?->error(
                'No fake_data fixtures found - run `python fake-data/generate_fake_data.py` first.'
            );

            return;
        }

        foreach (self::TABLE_ORDER as $table) {
            $table === 'user_roles' ? $this->loadUserRoles() : $this->loadTable($table);
        }

        $this->linkManuscriptCurrentVersions();
        $this->resetSequences();
        
        $this->command?->info('Generating articles from published manuscripts...');
        $this->generateArticles();

        $this->command?->info('Fake data seeding complete.');
    }

    private function generateArticles(): void
    {
        DB::statement("
            INSERT INTO articles (manuscript_id, issue_id, source_version_id, doi, page_start, page_end, pdf_path, published_at)
            SELECT 
                m.id, 
                (SELECT id FROM issues WHERE journal_id = m.journal_id ORDER BY random() LIMIT 1), 
                m.current_version_id, 
                '10.1234/jpms.' || m.id, 
                1, 
                20, 
                'sample_01.pdf', 
                m.updated_at
            FROM manuscripts m 
            WHERE m.status = 'Published'
        ");
    }

    private function fixture(string $name): ?array
    {
        $path = self::FIXTURE_DIR."/{$name}.json";

        if (! is_file($path)) {
            return null;
        }

        return json_decode(file_get_contents($path), true);
    }

    private function loadTable(string $table): void
    {
        $data = $this->fixture($table);

        if (! $data) {
            return;
        }

        $columns = $data['columns'];
        $isAudited = array_key_exists($table, self::AUDIT_TABLES);
        $auditColumn = self::AUDIT_TABLES[$table] ?? null;
        $entityType = self::ENTITY_TYPES[$table] ?? null;

        foreach (array_chunk($data['rows'], self::CHUNK_SIZE) as $chunk) {
            $assocRows = array_map(fn (array $row) => array_combine($columns, $row), $chunk);
            DB::table($table)->insert($assocRows);

            if ($isAudited && ! self::SKIP_AUDIT_LOG) {
                $this->emitAuditLogs($entityType, $auditColumn, $assocRows);
            }
        }

        $this->command?->info("{$table}: ".count($data['rows']).' rows');
    }

    private function loadUserRoles(): void
    {
        $data = $this->fixture('user_roles');

        if (! $data) {
            return;
        }

        $roleIds = DB::table('roles')->pluck('id', 'role_name');
        $columns = $data['columns']; // id, user_id, journal_id, role_name
        $entityType = self::ENTITY_TYPES['user_roles'];

        foreach (array_chunk($data['rows'], self::CHUNK_SIZE) as $chunk) {
            $assocRows = [];

            foreach ($chunk as $row) {
                $r = array_combine($columns, $row);
                $assocRows[] = [
                    'id' => $r['id'],
                    'user_id' => $r['user_id'],
                    'journal_id' => $r['journal_id'],
                    'role_id' => $roleIds[$r['role_name']],
                ];
            }

            DB::table('user_roles')->insert($assocRows);
            if (! self::SKIP_AUDIT_LOG) {
                $this->emitAuditLogs($entityType, null, $assocRows);
            }
        }

        $this->command?->info('user_roles: '.count($data['rows']).' rows');
    }

    /** @param  array<int, array<string, mixed>>  $rows */
    private function emitAuditLogs(string $entityType, ?string $auditColumn, array $rows): void
    {
        $now = now();
        $docs = [];

        foreach ($rows as $row) {
            // Always a Carbon instance (never a raw string) so every doc's
            // created_at stores as a proper BSON date, not a mix of BSON
            // strings and dates that would sort/compare inconsistently.
            $createdAt = ($auditColumn && ! empty($row[$auditColumn])) ? \Carbon\Carbon::parse($row[$auditColumn]) : $now;
            $docs[] = [
                'user_id' => null,
                'entity_type' => $entityType,
                'entity_id' => $row['id'],
                'action' => 'created',
                'old_value' => null,
                'new_value' => json_encode($row),
                'created_at' => $createdAt,
            ];
        }

        AuditLog::insert($docs);
    }

    private function linkManuscriptCurrentVersions(): void
    {
        $data = $this->fixture('manuscript_current_version_links');

        if (! $data) {
            return;
        }

        foreach (array_chunk($data['rows'], 2000) as $chunk) {
            $values = implode(', ', array_map(fn (array $r) => "({$r[0]},{$r[1]})", $chunk));
            DB::statement(
                'UPDATE manuscripts AS m SET current_version_id = t.vid '.
                "FROM (VALUES {$values}) AS t(id, vid) WHERE m.id = t.id"
            );
        }
    }

    private function resetSequences(): void
    {
        foreach (self::SEQUENCE_TABLES as $table) {
            DB::statement(
                "SELECT setval(pg_get_serial_sequence('{$table}', 'id'), ".
                "COALESCE((SELECT MAX(id) FROM {$table}), 1))"
            );
        }
    }
}
